SU-SWS/sulgryphon-nextjs

components/layouts/main-content-layout.tsx
components/menu/main-menu.tsx
components/nodes/node-stanford-news.tsx
components/paragraphs/stanford-card.tsx
components/paragraphs/stanford-media-caption.tsx
components/paragraphs/stanford-wysiwyg.tsx
components/simple/oembed.tsx
lib/format-html.tsx
lib/menu.tsx
lib/use-on-screen.tsx
pages/404.tsx
pages/[...slug].tsx
pages/_app.tsx
pages/api/menu.tsx
pages/index.tsx
styles/globals.css

- refactored the way to fetch the main menu items.
- Adjusted the oembed display to only load when the content is in view
- Fixed the embeddable content in the wysiwyg
- Fixed embedded image in wysiwyg with captions
- Provided a new hook `useOnScreen` to make in view visible elements easier to build
1. view the preview build pages:
- https://deploy-preview-23--stanford-library.netlify.app/test-content/test-text-area-content/test-embeddable-content
- https://library-dev.sites-pro.stanford.edu/node/106/edit
- https://deploy-preview-23--stanford-library.netlify.app/test-content/test-text-area-content
- https://library-dev.sites-pro.stanford.edu/node/81/edit
2. Verify they look as expected compared to the BE side

Better Oembed Handling for paragraphs and wysiwyg

---

src/components/nodes/node-stanford-event-series.tsx

- [SUL23-39](https://stanfordits.atlassian.net/browse/SUL23-39): Build "Event Series" content display in NextJS
1. Checkout branch
2. Create a few example events
3. Create an example Event Series featuring your example events.
4. Compare with [D9](https://userguidetest20210222.sites.stanford.edu/event/series/sws-test-1126-event-series).
5. You can see the event series card by selecting it using the teaser paragraph, or adding a "shared tags" card list. See the bottom of [this page](https://userguidetest20210222.sites.stanford.edu/sws-test-1118-events-lists) for how it appears in D9.
6. It doesn't appear the `NodeStanfordEventSeriesListItem` is be used, so I didn't build that out.
- Does this PR impact any particular …

SUL23-39 | @jdwjdwjdw | Build "Event Series" content display

---

src/components/nodes/node-stanford-course.tsx

- [SUL23-37](https://stanfordits.atlassian.net/browse/SUL23-37): FE-DEV | Build "Course" content display in NextJS
- As noted on this ticket, we're not styling the node section
- [SUL23-44](https://stanfordits.atlassian.net/browse/SUL23-44): FE-DEV | Build "Course" card display in NextJS
- [SUL23-51](https://stanfordits.atlassian.net/browse/SUL23-51): FE-DEV | Build "Course" list item display in NextJS
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` them …

SUL23-37, SUL23-44, SUL23-51 | @jdwjdwjdw | Build "Course" content display

---

src/components/nodes/node-stanford-page.tsx

- Fix line height issue with text being cut off in the select by adding `su-leading-display`
- Fix issue where card width was changing based on the text length of the library branch options
1. Checkout branch or view preview at https://deploy-preview-46--stanford-library.netlify.app/
2. Confirm that select text is no longer cut off, and card width looks good.
- JIRA ticket
- Other PRs

SUL-000 | @jdwjdwjdw | Fix up homepage banner select width and text being cut off

---

src/components/nodes/node-stanford-publication.tsx
src/components/patterns/card.tsx

- [SUL23-42](https://stanfordits.atlassian.net/browse/SUL23-42): FE-DEV | Build "Publication" content display in NextJS
- [SUL23-49](https://stanfordits.atlassian.net/browse/SUL23-49): FE-DEV | Build "Publication" card display in NextJS
- Per our discussion during SUL standup, this PR is only focusing on the Publication node and card displays. See [SUL23-56](https://stanfordits.atlassian.net/browse/SUL23-56) for future work on the Publications list display.
1. Checkout branch or view preview at https://deploy-preview-47--stanford-library.netlify.app/
2. Create example publications and a basic page with publication teasers, or view examples:
https://deploy-preview-47--stanford-library.netlify.app/publications/white-paper/sws-test-pub-217-article-newspapermagazine …

SUL23-42 | @jdwjdwjdw | Build Publication content display in NextJS

---

app/(public)/components/node/sul-library/library-hours.tsx
app/(public)/components/views/study-places.tsx

- Set `isSearchable` to false for React Select
1. View React Select list on Branch page or Places to Study page, and confirm that it's not searchable

SUL23-000 | @jdwjdwjdw | Fixup for React Select

---

app/(public)/[...slug]/page.tsx

- Turn off time based revalidation so that only on-demand revalidation happens
- Opt out of fetch and other library caches
- When you can
- ?

NoJira: On demand revalidation only and no caching requests.

---

src/components/views/sul-study-place/study-place-filtering.tsx

- TL;DR - what's this PR for? Accessibility
- TIcket: https://stanfordits.atlassian.net/jira/software/c/projects/SUL23/boards/391?selectedIssue=SUL23-289
Jan 23
- Low
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

sul23-289 - aria atomic

---

src/components/node/stanford-event/card.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-428
- Swapped 16/9 event card images for 4/3. 
- April 19
1. Review on build. https://su-library-git-sul23-428-event-images-d63b14-stanford-libraries.vercel.app/news-and-events
- JIRA ticket
- Other PRs

SUL23-428 - events ratio to 4/3

---

src/components/node/sul-library/library-header.tsx
src/components/paragraph/sul-contact-card/node-reference-card-hours.tsx

- The cards on this page for the See all hours. https://library.stanford.edu/libraries-0/branches-and-centers
- The banner card on this page. https://library.stanford.edu/libraries/cecil-h-green-library
- 5/17
- High
1. Open the PR
2. Use Chrome. Make sure you have the Wave plugin added. 
3. Got to the /libraries-0/branches-and-centers on your local or Vercel build. 
4. Open Wave plugin. You will get a panel on the left side of the screen. Go to to the order tab.  Look at item 18 to start.
5. Verify in the Wave that the words have a space in the tool but not visible in the UI. 
6. 
**7. What it looked like before.**
9. Library header card: https://su-library-git-sul23-450-missing-space-stanford-libraries.vercel.app/libraries/academy-hall-redwood-city-campus
**11. Where the error is on …

SUL23-450: Adding space in card

---

src/components/node/stanford-event/card.tsx
src/components/node/stanford-news/card.tsx

- Changed line height on headings for the News and Events cards.
- 5/22
- Normal
1. Open the Vercel site.
1. Look at the cards for News and Event on the homepage: https://su-library-git-sul23-467-line-height-stanford-libraries.vercel.app/
3. Verify the heading/title is `1.4` and not `1.2`.
4. The cards are all over the site and can be seen on the Library individual pages too. 
[- SUL23-467](https://stanfordits.atlassian.net/browse/SUL23-467)

SUL23-467: Changed line height on News and Event cards

---

src/components/patterns/modals/interception-modal.tsx
src/components/patterns/modals/modal.tsx

- Moved the close button higher up within the html to better support focus order in a dialog. 
- 5/22
- normal
1. Look at the build - https://su-library-git-sul23-461-focus-order-stanford-libraries.vercel.app/people/zoe-dilles
2. Try the search modal on any page.
3. Verify the close button is before the form for focus.
4. Go to this page: https://su-library-git-sul23-461-focus-order-stanford-libraries.vercel.app/people/zoe-dilles
5. Click the appointment scheduler.
6. Verify the close button is before the form for focus.
[- SUL23-461](https://stanfordits.atlassian.net/browse/SUL23-461)

SUL23-461: Moved button for focus order

---

app/page.tsx

- Moved the HP last changed date a little more
- asap
- normal, but maybe a hotfix
1. go here: https://su-library-git-sul23-431-v2-date-padding-stanford-libraries.vercel.app/
2. Verify the last updated at the bottom of the HP has a little more top padding. 
- JIRA ticket
- Other PRs

SUL23-431: version 2 of date padding

---

src/components/node/stanford-page/home-page/home-page-banner.tsx
src/components/node/stanford-page/home-page/today-hours.tsx

- Added a map link to the homepage branches box.
2. Navigate to the home page. 
3. Select a branch from the dropdown in the top area of the page.
4. verify a map icon and link appears.  Verify the link goes to a map to the chosen branch
5. Select a different library branch. Verify the link now goes to the newly-selected branch map.
- Other PRs
- …

SUL23-438: Added location link to list of branches on the homepage

---

app/api/library-hours/route.tsx

- Use the unstable cache to store library hours data instead of fetch
- Adjust invalidation for the api route to reduce cache calls

Adjust how library hours data is cached to reduce cache writes/reads

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Places to study page, the branch name and link was missing the hover state.
- 8/13
- normal
1. Navigate to https://su-library-git-sul23-598-places-hover-stanford-libraries.vercel.app/test-list-page
4. Verify the branch name hover on the Places to Study page is the same as other links. 
[- SUL23-598](https://stanfordits.atlassian.net/browse/SUL23-598)
- …

SUL23-598: fixup up hover on branch name

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- Changed the padding-left to be 80px on xl and 20px on lg and up.  
- 8/26
- Normal
- Normal
1. Navigate to https://su-library-git-sul23-608-address-stanford-libraries.vercel.app/test-list-page
4. Verify the address on the branches table no longer runs off the screen and is hidden.
[- SUL23-608](https://stanfordits.atlassian.net/browse/SUL23-608)
- [Browserstack](https://live.browserstack.com/dashboard) and …

SUL23-608: changed the padding-left when the browser size is smaller

---

src/components/node/stanford-page/home-page/today-hours.tsx

- changed the padding-bottom on the hours card on the hompage
- 8/29
- Normal
- Normal
1. Navigate to https://su-library-git-sul23-609-hours-spacing-stanford-libraries.vercel.app/
4. Verify text in card does not run off the card in responsive sizes. 
5. Try different libraries to see how it wraps in the select. 
[- SUL23-609](https://stanfordits.atlassian.net/browse/SUL23-609)
- …

SUL23-609: fix to text in hours card on homepage

---

src/components/node/stanford-news/page-display.tsx

- The caption was on the page but hidden under the image. I didn't verify it wasn't on the page. 
- Possibly remove the fragment added?
- 9/18
- Normal
- Normal
1. Navigate to /news/stanford-libraries-make-nuremberg-international-military-tribunal-trial-archives-1945-1946
4. Verify there is a visible caption
5. Review the solution. 
[- SUL23-480](https://stanfordits.atlassian.net/browse/SUL23-480)
- …

SUL23-480: caption missing but really under the image

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- add Reservation not required to places to study with no reservation button
1. Navigate to Places to Study
4. Verify that the "Reservation not required" text appears when there is no reservation link available 
5. Review code
- SUL23-650

SUL23-650 | add Reservation not required to places to study with no reservation button

---

src/components/node/stanford-news/card.tsx
src/components/patterns/elements/select-list.tsx
src/components/views/stanford-news/filtering-news-card-view.client.tsx

- SUL23-662 | adjust news filters
2. Update News List to the Filter News List
3. Navigate to News
4. Verify that the filters and grid appears like the [mock](https://www.figma.com/design/E6rFFnHIs7ch0oK5j9C1Wc/Tabular-view-and-Filtering?node-id=1636-3090&t=qFdTooFA7VW7ssLd-1)
5. Review code
- SUL23-662

SUL23-662 | adjust news filters

---

src/components/paragraph/stanford-card.tsx
src/components/patterns/horizontal-card.tsx

- SUL23-665 | resolve overlapping card image for certain breakpoints
1. Navigate to preview: https://su-library-git-bug-sul23-665-card-stanford-libraries.vercel.app/libraries/east-asia-library
2. Test different screen sizes and confirm that the horizontal card image doesn't overlap the paragraph items above
3. Review code
- SUL23-665 | resolve overlapping card image for certain breakpoints

SUL23-665 | resolve overlapping card image for certain breakpoints

---

src/lib/format-html.tsx

- nojira | fix media fig caption error
- Before release
- High
2. Spin up local
3. Navigate to `/news/les-paroles-politiques-cherubini-celebrates-louis-xviii`
4. Verify that the embed spans full width and the media image captions appear normal
5. Review code
- SUL23-663

nojira | fix media fig caption error

---

src/components/menu/fallback-main-menu.tsx
src/components/menu/main-menu.tsx

- SUL23-698 | fixup about us menu item display
1. Navigate to the [preview site](https://su-library-git-bug-sul23-698-nav-stanford-libraries.vercel.app/) on Firefox
4. Verify that the About Us doesn't break into two lines when changing the screen width
5. Review code
- SUL23-698

SUL23-698 | fixup about us menu item display

---

src/components/paragraph/sul-home-banner/sul-home-banner.client.tsx
vercel.json

- SUL23-748 | add catalog and articles searchwork options to hero search
1. Navigate to https://su-library-git-feature-sul23-748-stanford-libraries.vercel.app/
2. Verify that when searching for Catalog or Article+, you are redirected to searchworks
3. Review code
- SUL23-748 | add catalog and articles searchwork options to hero search

SUL23-748 | add catalog and articles searchwork options to hero search

---

src/components/menu/main-menu.tsx

- SUL23-765 | ensure that text breaks into new line when it exceeds nest menu item width
1. Navigate to https://su-library-git-bug-sul23-765-stanford-libraries.vercel.app/
2. Verify that the secondary menu link under `About us` > `Support the Library...` link appears on two lines
3. Review code
- SUL23-765

SUL23-765 | ensure that text breaks into new line when it exceeds nest menu item width

---

src/components/patterns/card.tsx
src/lib/format-html.tsx

- SUL23-773 SUL23-774 | resolve media image center bug and site improve overflow hidden issue
- EOD Monday 04/28/25
1. Navigate to homepage preview: https://su-library-git-bug-sul23-773-774-stanford-libraries.vercel.app/
2. Verify that the cards appear the same as production (I removed `overflow-hidden` for SI purposes; it seems like that style has no impact on the cards. 🤔 )
3. Navigate to a news page with an image: https://su-library-git-bug-sul23-773-774-stanford-libraries.vercel.app/news/david-harris-archive
4. Verify that the bottom image is centered (compared to prod: https://library.stanford.edu/news/david-harris-archive)
5. Review code 🌱 
- SUL23-773
- SUL23-774

SUL23-773 SUL23-774 | resolve media image center bug and site improve overflow hidden issue

---

src/lib/format-html.tsx
src/styles/tailwind/plugins/base/base.js

- SUL23-769 | fixup conflicting wysiwyg styles
(This resolves the `text-16 sm:text-18` typography overriding the styles)
1. Review code
2. Navigate to http://su-library-git-bug-sul23-769-stanford-libraries.vercel.app/research-support/data-support-and-services
3. Verify that the intro/sub title style appears
4. Bonus: Pull code down to local and create a page with all the text styles
- SUL23-769

SUL23-769 | fixup conflicting wysiwyg styles

---

app/[...slug]/page.tsx
src/components/node/stanford-news/page-display.tsx
src/components/node/stanford-person/page-display.tsx
src/components/patterns/elements/number-link.tsx
src/components/patterns/internal-header-banner.tsx

- rework page header for basic, person, and news content types
- EOD Thursday, 5/22
1. Navigate to
2. Verify that the heading matches the [figma](https://www.figma.com/design/yr0Nd7t7qGW4S95OtSCqa3/Secondary-page---header-and-people?node-id=129-2529&t=7Alo5bi5HZgdeajt-1)
3. Navigate to https://su-library-git-feature-sul23-793-stanford-libraries.vercel.app/people/first-last
4. Verify that the heading and body content matches [figma](https://www.figma.com/design/yr0Nd7t7qGW4S95OtSCqa3/Secondary-page---header-and-people?node-id=127-2542&t=7Alo5bi5HZgdeajt-1). _Note:_ I plan to review certain fields that weren't account for in mocks with Darcy during our FE Sync on Friday
5. Navigate to https://su-library-git-feature-sul23-793-stanford-libraries.vercel.app/news/new-japanese-studies-librarian-k …

SUL23-793 SUL23-794 SUL23-795 | rework page header for basic, person, and news content types

---

src/components/layout/header.tsx

- SUL23-788 | prevent searchworks catalog link from line break
- EOD Thursday, 05/22
2. Verify that SearchWorks Catalog link doesn't break into two lines
3. Review code 🌱 
- SUL23-788

SUL23-788 | prevent searchworks catalog link from line break
