SU-SWS/sulgryphon-nextjs

.eslintrc.json
.github/workflows/build_lint.yml
components/layouts/main-content-layout.tsx
components/layouts/one-column.tsx
components/layouts/three-column.tsx
components/layouts/two-column.tsx
components/menu/main-menu.tsx
components/nodes/node-stanford-event.tsx
components/paragraphs/row.tsx
components/paragraphs/stanford-banner.tsx
components/paragraphs/stanford-card.tsx
components/paragraphs/stanford-image-gallery.tsx
components/paragraphs/stanford-lists.tsx
components/paragraphs/stanford-media-caption.tsx
components/paragraphs/stanford-spacer.tsx
components/patterns/banner.tsx
components/patterns/card.tsx
components/patterns/lockup.tsx
components/simple/image.tsx
components/simple/link.tsx
components/simple/modal.tsx
lib/format-html.tsx
lib/menu.tsx
next.config.js
package.json
pages/[...slug].tsx
styles/globals.css
yarn.lock

- Styled the different paragraph types in the basic page
- fixed various wysiwyg markup issues
- :shrug: 
- medium
1. checkout this branch
2. `yarn dev`
3. Create a basic page
4. populate it with any of the paragraph types except lists & teasers
5. compare the results to an existing drupal site.
<a href="https://gitpod.io/#https://github.com/SU-SWS/sulgryphon-nextjs/pull/7"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

SUL23 36 Style Basic page and paragraphs

---

pages/admin/paragraph/[id].tsx

- SUL23-43 Style the basic page card and list items
- better SEO metadata
- Added title template
- added default title
- Route to preview paragraphs
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
<a href="https://gitpod.io/#https://github.com/SU-SWS/sulgryphon-nextjs/pull/16"><img …

paragraph preview

---

next.config.js
public/robots.txt
src/components/nodes/node-stanford-event.tsx
src/components/paragraphs/stanford-card.tsx
src/components/paragraphs/stanford-entity.tsx
src/components/patterns/card.tsx
src/components/simple/link.tsx
src/lib/format-html.tsx
src/types/drupal.d.ts

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23-113 Fix link/button styles and scaffold the background behaviors

---

src/components/nodes/node-stanford-person.tsx
src/components/paragraphs/stanford-lists.tsx
src/types/drupal.d.ts

- [SUL23-41](https://stanfordits.atlassian.net/browse/SUL23-41): FE-DEV | Build "Person" content display in NextJS
- [SUL23-48](https://stanfordits.atlassian.net/browse/SUL23-48): FE-DEV | Build "Person" card display in NextJS
- [SUL23-55](https://stanfordits.atlassian.net/browse/SUL23-55): FE-DEV | Build "Person" list item display in NextJS
1. Checkout branch
2. Create some example people
3. Create basic page with person list and teasers
4. Confirm that person node page, cards and teasers look good.
5. Review code 🤖 
- [SUL23-41](https://stanfordits.atlassian.net/browse/SUL23-41): FE-DEV | Build "Person" content display in NextJS
- [SUL23-48](https://stanfordits.atlassian.net/browse/SUL23-48): FE-DEV | Build "Person" card display in NextJS
- …

SUL23-41, SUL23-48, SUL23-55 | @jdwjdwjdw | build person node, list, and card

---

src/components/nodes/node-sul-library.tsx
src/lib/hooks/useLibraryHours.tsx

- [SUL23-70](https://stanfordits.atlassian.net/browse/SUL23-70): FE-DEV | Build and style the branch pages
1. Checkout branch or view [preview](https://deploy-preview-44--stanford-library.netlify.app/sample-content/david-rumsey-map-center)
2. Create library branch page
3. Confirm everything looks correct, including responsive
4. Review code ☕
[SUL23-70]: https://stanfordits.atlassian.net/browse/SUL23-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SUL23-70 | @jdwjdwjdw | Build and style the library branch pages

---

package.json
src/components/nodes/node-sul-study-place.tsx
src/components/paragraphs/stanford-lists.tsx
src/components/views/study-places.tsx
yarn.lock

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23-71 Stubbed out study place filtering list

---

package-lock.json
package.json
src/components/nodes/node-stanford-person.tsx
yarn.lock

- Add sizeMe package, update person card based on container width
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Add sizeMe, add ternary conditional

---

package-lock.json
package.json
src/components/nodes/node-stanford-person.tsx
yarn.lock

- [SUL23-126: FE-DEV | Adjust "Person" card display to align with designs](https://stanfordits.atlassian.net/jira/people/557058%3A846652ea-d36e-4d63-ba7a-4d9c3463d1a8/boards/246?modal=detail&selectedIssue=SUL23-126)
- Added [react-sizeme](https://github.com/ctrlplusb/react-sizeme) package in order to update styles based on container width.
- Small fixups to the person list display
1. Checkout branch or [view preview](https://deploy-preview-49--stanford-library.netlify.app/)
2. Create a basic page with person teasers or view https://deploy-preview-49--stanford-library.netlify.app/sample-content/paragraph-components/person-teaser (compare with https://library-netlify.stanford.edu/sample-content/paragraph-components/person-teaser). Test with side-menu and no side-menu.
3. …

SUL23-126 | @jdwjdwjdw | Adjust Person card display

---

src/components/nodes/node-sul-library.tsx

- [SUL23-125](https://stanfordits.atlassian.net/browse/SUL23-125): FE-DEV | Update branch content type to include center functionality
1. Checkout branch or view [preview](https://deploy-preview-52--stanford-library.netlify.app/)
2. Generate branch locations of both `branch` and `center` type, or view preview examples for a [branch](https://deploy-preview-52--stanford-library.netlify.app/libraries/sws-test-323-example-branch-academy-hall) and [center](https://deploy-preview-52--stanford-library.netlify.app/libraries/branch-location-acsi-consectetuer-enim-exerci)
3. Confirm that they appear as specified (if Branch Page: site-visitor display will include custom page header/title with feature image and drop-down for hours. if Center Page: site-visitor display will be that …

SUL23-125 | @jdwjdwjdw | Update branch content type to include center functionality

---

src/components/paragraphs/stanford-card.tsx
src/components/patterns/card.tsx
src/components/simple/link.tsx
src/types/drupal.d.ts

- Updated FE for card link style variants: https://stanfordits.atlassian.net/browse/SUL23-128
- Med
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23-128-three-card-link-styles

---

.github/workflows/build_lint.yml
.github/workflows/update-dev-test-branches.yml
app/(public)/[...slug]/layout.tsx
app/(public)/[...slug]/page.tsx
app/(public)/components/node/stanford-event-series/page-display.tsx
app/(public)/components/node/stanford-event/page-display.tsx
app/(public)/components/node/stanford-news/page-display.tsx
app/(public)/components/node/stanford-page/home-page/page-display.tsx
app/(public)/components/node/stanford-page/page-display.tsx
app/(public)/components/node/stanford-person/page-display.tsx
app/(public)/components/node/stanford-publication/page-display.tsx
app/(public)/components/node/sul-library/page-display.tsx
app/(public)/components/paragraph/index.tsx
app/(public)/error.tsx
app/(public)/layout.tsx
app/(public)/lib/fetch-components.tsx
app/(public)/lib/format-date.tsx
app/(public)/page.tsx
src/pages/api/preview.tsx
yarn.lock

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Provide authentication for page previews

---

app/(public)/components/paragraph/index.tsx
app/(public)/components/paragraph/sul-contact-card.tsx
app/(public)/lib/hooks/useLibraryHours.tsx

- [SUL23-118](https://stanfordits.atlassian.net/browse/SUL23-118): FE-DEV | style Contact Card Paragraph
1. Checkout branch or view preview at https://deploy-preview-56--stanford-library.netlify.app/sws-test-314-contact-card-paragraph?slug=/sws-test-314-contact-card-paragraph
2. Add contact card paragraphs (None, Branch, and Center) to a basic page, or review [preview](https://deploy-preview-56--stanford-library.netlify.app/sws-test-314-contact-card-paragraph?slug=/sws-test-314-contact-card-paragraph)
3. Confirm all looks good, including responsive
4. Review code 🥪 
- [SUL23-118](https://stanfordits.atlassian.net/browse/SUL23-118): FE-DEV | style Contact Card Paragraph
[SUL23-118]: https://stanfordits.atlassian.net/browse/SUL23-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

SUL23-118 | @jdwjdwjdw | style Contact Card Paragraph

---

app/(public)/components/paragraph/rows/one-column.tsx
app/(public)/components/paragraph/stanford-card.tsx
app/(public)/components/patterns/card-sprinkles.tsx
app/(public)/components/patterns/card.tsx
app/(public)/components/patterns/horizontal-card.tsx

- SUL23-115 - Horizonal logic
- Adding styling.
- Image options.
- Additional sprinkle tsx
- sul23-115 - fixed mobile sprinkles.
- sul23-115 - fixed mobile sprinkles.
- removed image
- sul23-115 - tweak bg top right image.
- sul23-115 - tweak bg top right image.
- sul23-115 - fixing horizontal issue.
- SUL23-115 - fixed merged.
- Merge 1.x
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` …

SUL23 115 feedback

---

app/(public)/[...slug]/page.tsx
app/(public)/components/menu/fallback-main-menu.tsx
app/(public)/components/menu/main-menu.tsx
app/(public)/editori11y.tsx
app/(public)/layout.tsx
app/(public)/lib/fetch-components.tsx
src/middleware.tsx

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Added Editorially if coming from drupal api/preview iframe

---

app/(public)/[...slug]/layout.tsx
app/(public)/[...slug]/page.tsx
app/(public)/layout.tsx
app/layout.tsx
components/layout/library-footer.tsx
components/node/stanford-course/card.tsx
components/node/stanford-course/list-item.tsx
components/node/stanford-event-series/card.tsx
components/node/stanford-person/horizontal-card.tsx
components/node/stanford-person/vertical-card.tsx
components/node/stanford-publication/card.tsx
components/node/sul-study-place/study-place-features.tsx
components/paragraph/stanford-banner.tsx
components/paragraph/stanford-entity.tsx
components/paragraph/stanford-image-gallery.tsx
components/paragraph/stanford-media-caption.tsx
components/paragraph/sul-collection.tsx
components/paragraph/sul-libguides.tsx
components/patterns/card.tsx
yarn.lock

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Trigger build

---

app/(public)/[...slug]/page.tsx
components/node/stanford-person/libcal.tsx
components/node/stanford-person/page-display.tsx
package.json
yarn.lock

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Updated dependencies

---

components/node/stanford-page/home-page/today-hours.tsx
components/patterns/elements/select-list.tsx
components/views/sul-study-place/study-place-filtering.tsx
package.json
yarn.lock

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Refactor select lists using mui

---

components/menu/main-menu.tsx
components/node/stanford-page/home-page/home-page-banner.tsx
components/search/search-modal.tsx
next.config.js
vercel.json

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Rewrite /all for discover domain

---

components/layout/library-footer.tsx

- Link to root of domain
- Soon
- Med-high
1. Check out the [preview build](https://su-library-git-nojira-footerlink-stanford-libraries.vercel.app/)
2. Click into a nested page
3. Click the footer link

Fixup: Footer link relative path.

---

src/components/views/sul-study-place/study-place-filtering.tsx

- Simple text and style update: https://stanfordits.atlassian.net/browse/SUL23-408
- Styled "Showing X of 32"

SUL23-408 - Styling tweak and filter text instruction.

---

src/components/node/sul-library/library-hours.tsx

- Current wording causing confusion as to when closure actually occurs on branch location pages. This is to clarify.  
- https://stanfordits.atlassian.net/browse/SUL23-404
- Feb 14
mid

SUL23-404 - branch pages update to text for hours closed/open

---

src/components/patterns/link.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-283
- Summary: add hover/focus styles to action links!
- February 20
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Sul23-283 -- inline hover state

---

src/components/node/sul-library/page-display.tsx

- February 21
1. Do this
1. Then this
2. Then this

Sul23 418 accessibility additional hour element

---

src/components/paragraph/stanford-lists.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-415
- See title.
ASAP

SUL23-415 - Reduced the spacing above H2s

---

src/components/node/stanford-event/card.tsx
src/components/node/stanford-news/card.tsx
src/components/node/sul-study-place/card.tsx
src/components/node/sul-study-place/study-place-features.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-414
- See title
ASAP

Swapping rations for card images.

---

src/components/views/card-list.tsx

- Reduced the gap between cards.
- Ticket: https://stanfordits.atlassian.net/browse/SUL23-413
ASAP

SUL23-413 - Reduced gap spacing

---

src/components/node/stanford-person/libguide.tsx

- Scaling up guides for persons. 
- Ticket: https://stanfordits.atlassian.net/browse/SUL23-346
March 8
Mid
1. Do this
1. Then this
2. Then this

SUL23-346 - Lbguides Includes

---

src/components/layout/library-footer.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-425
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23 - 425 footer h2

---

src/components/layout/library-footer.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-424
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23-424 - careers link footer

---

src/components/node/sul-library/page-display.tsx

- Ticket: https://stanfordits.atlassian.net/browse/SUL23-418

Removing card styles from accessibility.

---

src/components/node/stanford-event/card.tsx
src/components/node/stanford-news/card.tsx
src/styles/tailwind/plugins/base/base.js

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

SUL23-416 - reducing base font size for headers for md screen

---

src/components/layout/library-footer.tsx

- Career link is broken. Following Mike's idea of a redirect so the client can update.
- Ticket: https://stanfordits.atlassian.net/browse/SUL23-424

Adding career link for redirect.

---

.gitpod.yml

1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

Adjusted gitpod setup

---

.github/pull_request_template.md
app/page.tsx
app/search/search.tsx
src/components/node/stanford-news/page-display.tsx
src/components/node/stanford-page/page-display.tsx
src/components/node/stanford-person/page-display.tsx
src/components/node/sul-library/page-display.tsx

- I have it working on the different content types. I thought there might be a way to make this a component that is shared to each template. I wasn't quite sure how to do that. 
- I changed the search page to match the design.
- Updated the PR template.
- Added a changed on date to the bottom of each page.
- For June release
- Normal
2. Refresh
3. Navigate to each content type and verify there is a last updated 
4. Verify it is on all the types of pages and aligned as designed.
- Does this PR impact any …

SUL23-431: Adding an updated date on the Stanford page template

---

src/components/node/stanford-course/card.tsx
src/components/node/stanford-event/card.tsx
src/components/node/stanford-news/card.tsx
src/components/node/stanford-page/home-page/home-page-banner.tsx
src/components/node/stanford-person/horizontal-card.tsx
src/components/node/stanford-person/list-item.tsx
src/components/node/stanford-person/vertical-card.tsx
src/components/node/sul-study-place/card.tsx
src/components/node/sul-study-place/study-place-features.tsx
src/components/node/sul-study-place/study-place-today-hours.tsx
src/components/paragraph/stanford-entity.tsx
src/components/paragraph/sul-collection.tsx
src/components/paragraph/sul-contact-card/manual-fields-card.tsx
src/components/paragraph/sul-contact-card/node-reference-card-hours.tsx
src/components/paragraph/sul-contact-card/node-reference-card.tsx
src/components/paragraph/sul-featured-collection.tsx
src/components/patterns/banner.tsx
src/components/patterns/card.tsx
src/components/patterns/horizontal-card.tsx
src/components/views/card-list.tsx
src/components/views/sul-study-place/study-place-filtering.tsx
src/styles/tailwind/plugins/base/base.js

- Moved designer's changes in a pr.
- Tightened up spacing and font sizes
- 5/16
- high
1. Checkout this branch.
2. Clear caches.
3. Verify the fonts are smaller and spacing tightened up. 
[- SUL23-451](https://stanfordits.atlassian.net/browse/SUL23-451)

SUL23-451: Moved Alan's edits to repo.

---

app/page.tsx

4. Verify...
- Other PRs
- Anyone who should be notified? …

Release 1.2.1

---

src/components/views/view.tsx

- We needed to map the fields from a `NodeStanfordPerson` in such a way as they ended up in the shape of a `TablePerson` object in the `sul-people-table-view.tsx` file.  Following the pattern in the `view.tsx` file, I mapped the fields correctly.
4. Verify...
- Other PRs …

Mapped NodeStanfordPerson correctly for table view

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- The column headings were missing from the Large breakpoint.
- Medium and Small do not have column headings visible.
- 6/30
- Normal
- Normal
3. Navigate to a page with the branches and locations tablular data. 
5. Verify there is a table heading at LG and up.
6. Verify the headings are not visible on MD and smaller. 
[- SUL23-516](https://stanfordits.atlassian.net/browse/SUL23-516)
- …

SUL23-516: added col headings back to the table

---

src/components/views/sul-people/sul-people-table-view.tsx
src/styles/globals.css

- Small breakpoint has less space.
- Moved the padding from the global.css to the tsx file for better responsiveness
- Fixed medium breakpoint to the image left and text to right
- Fixed the label on the toggle since was in the file. 
- Fixed the font face on the name.
- 7/1
- Normal
- Normal
3. Navigate to a page with the people table.
4. Verify the small breakpoint is tighter in spacing.
5. Verify the med breakpoint is 2 columns
6. Verify the label is updated to the right specialist name. 
[- SUL23-521](https://stanfordits.atlassian.net/browse/SUL23-521)
[- SUL23-522](https://stanfordits.atlassian.net/browse/SUL23-522) …

SUL23-521 & SUL23-522: Fixed the sm and med breakpoints

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Added padding on the background color for the features content in the xs to md breakpoints.
- 627
-Normal
-Normal
3. Navigate to to a page with the Places to Study table.  
4. Review the toggle for All Locations and Open Now. 
5. Verify when clicked you have a 2px border and grey background
6. Verity the toggle turns off an on.
[- SUL23-506](https://stanfordits.atlassian.net/browse/SUL23-506)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEP …

SUL23-506: Fix to toggle outline on study places

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Added padding on the background color for the features content in the xs to md breakpoints.
- 627
-Normal
-Normal
3. Navigate to to a page with the Places to Study table.  
4. Reduce window size to Med and smaller
5. Verify the block with the features has a grey background with a padding:16px 8px
[- SUL23-508](https://stanfordits.atlassian.net/browse/SUL23-508)
- [HTML …

SUL23-508: fixed bgcolor on features for md and down

---

src/components/patterns/elements/address.tsx
src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- Added the pin icon in front of the address.
- Removed the US from the address
- 6/30
- Normal
- Normal
2. Navigate to branch locations table. 
4. Verify there is a map pin icon
5. Verify the US isn't at the end of the address.
[- SUL23-520](https://stanfordits.atlassian.net/browse/SUL23-520) …

SUL23-520: Added the pin and removed the US from address

---

src/components/views/sul-people/libcal.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Fixed the Schedule button on Specialists and Places to study tables.
- 7/3
- Normal
- Normal
3. Navigate to page with the Study Places table and one with the Specialist table
4. Verify the button matches the design.  Cardinal red for the text. Hover/focus/active states have a bg of cardinal red with white text.
[- SUL23-524](https://stanfordits.atlassian.net/browse/SUL23-524)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharin …

SUL23-524: fixup to buttons

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- In the SM mobile, the open/closed should be on one line
- 7/1
- Normal
- Normal
3. Navigate to a branch table.
4. Look at the xs-sm and see the open and closed are on one line.
5. Check that the hours opens correctly for all the responsive sizes.
[- SUL23-518](https://stanfordits.atlassian.net/browse/SUL23-518)
- …

SUL23-518: Open/Closed on one line for sm mobile only

---

public/robots.txt

- added one line to the robots.txt
4. Verify...
- Other PRs
- [AMP …

SUL23-540: Updated robots.txt to disallow /all/

---

.github/workflows/build_lint.yml
.gitpod.yml

4. Verify...
- Other PRs
- Anyone who should be notified? …

Better automated tests & Gitpod by building a cloned site

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Fixes to the colors on the toggles
- Fixes to the font sizes to toggles.  They should be 16px but were 14px.  They are now 16.625 at the 2xl breakpoints.
- Fixed the subject specialist toggle to "Subject specialists"
- 7/18
- Normal
- Normal
3. Navigate to a page and create lists of the three type: Places to study, Research Specialists and Branches
4. Verify the toggles are all the same colors of grey and the same font sizes.
[- SUL23-515](https://stanfordits.atlassian.net/browse/SUL23-515)
[- SUL23-541](https://stanfordits.atlassian.net/browse/SUL23-541)
- …

SUL23-515 SUL23-541: Colors, fonts, word fixes to the toggles.

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
src/styles/globals.css

- Moved the medium breakpoint to a grid display to get the correct design. Originally we talked about using flex instead but it wasn't working to get the right display. The other option was `floats` and I think those are even less liked.
- I would like to use this technique for the Places to Study and People on the medium breakpoints. Both of those tables have the same spacing issue. I thought it was best to have it code reviewed in one place and then I can move the change to the other two tables.
- 7/18
- High
- High
3. Navigate to a list of Branches on a medium breakpoint.
4. Verify it looks like the design.
- Does this PR …

SUL23-525: Updates to the display for Med breakpoint on Branches and Centers

---

src/components/patterns/lockup.tsx

- added a space in the footer sr-only text.
- 7/23
- Normal
- Normal
3. Navigate to footer.  Turn on the Wave plugin for Chrome.
4. Verify there is a space between Stanford wordmark and site name
5. Images in the ticket for clarity.
[- SUL23-479](https://stanfordits.atlassian.net/browse/SUL23-479)
- …

SUL23-479: added space

---

src/components/views/sul-people/sul-people-table-view.tsx

- Made the TD not part of the condition so that when it was empty there was still a `<td>` 
- 7/19
- Normal
- Normal
3. Navigate to a people table. 
4. See that the td always appears even when empty.
5. Verify the table isn't collapsing the rows when there is missing content. 
[- SUL23-550](https://stanfordits.atlassian.net/browse/SUL23-550)
- [HTML …

SUL23-550: Move the condition so the td element remained even when empty

---

src/components/patterns/elements/select-list.tsx
src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Toggle hovers: removed underline and hover is a red underline and red board for all three tabular views.
- Toggles/Filters:  font size is 1.8rem.
- Filters: Changed rounded corners to rounded-3xl so filters when have something in them it isn't a circle line.
- - see the change on the homepage library select box for hours as well.
- Branches/Centers: Updated font size and weight and fixed the hover state. Needed to be 20px semibold (600 weight).
- Places to study: Title should be semi bold (600 weight)
- People/Specialists: Title should be font weight of 600 (semibold)
- All tables: All data need to be 16px and 400 weight
-- People all the data was 16px. - No change here.
-- Branches
-- Email changed to 16px and 400 weight.
-- Phone changed to 16px and 400 weight.
-- Study places:
-- …

SUL23-548 SUL23-553 SUL23-554 SUL23-555 SUL23-556 SUL23-547

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Added `tabindex=-1` to links on the photos for Specialists and  Branches too.
- Added `aria-hidden=true` to links on the photos for Specialists and  Branches too.
- Removed the link on the Places to Study Photo.
- Soon
- Normal
- Normal
3. Navigate to to the /test-list-page
4. Verify the photos are clickable with a mouse for Specialists and Branches.
5. Verify there is no link on the photo for the Places to Study.
6. Verify you see the code noted above on the photo.
[- SUL23-557](https://stanfordits.atlassian.net/browse/SUL23-557)
- [AMP …

SUL23-557: adding aria-hidden and tabindex for a11y to photos on tabular data tables

---

src/components/views/sul-people/sul-people-table-view.tsx

- Font size on search label needs to be 18px
- 7/25
- Normal
- Normal
3. Navigate to people table
4. Verify the search label is 18px
[- SUL23-503](https://stanfordits.atlassian.net/browse/SUL23-503) …

SUL23-503: search label font size

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- Changed the size of the address in the branch to size 16
- 7/26
- Normal
- Normal
3. Navigate to the branches page. 
4. Verify the address is size 16px.  it was 18px
[-  SUL23-579](https://stanfordits.atlassian.net/browse/SUL23-579) …

SUL23-579: changed address to size 16

---

src/components/menu/main-menu.tsx

- Fixup to the padding on main nav
- 7/26
- High
- High
3. Navigate to any page. 
4. Verify the red line only extends to edge of work.
5. Verify the dropdown menu aligns left with the topmost menu item.
6. Verify the mobile view has indentation in menu for sub items. 
[- SUL23-580](https://stanfordits.atlassian.net/browse/SUL23-580)
- [HTML …

SUL23-580: nav fixup

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Removed bold on specialists email on Specialists.
- Removed bold on library name links on Places to Study.
- Changed the line height to 23px on the data in the cell that is rendering at 16px
- 7/26
- Normal
- Normal
3. Navigate to test list page
4. Verify the line height change and the normal font change.
[- SUL23-556](https://stanfordits.atlassian.net/browse/SUL23-556)
- …

SUL23-556: normal font and leading

---

src/components/views/sul-people/sul-people-table-view.tsx

- Added padding between icons.
- Added the color
- Adjusted the size.

SUL23-503 Add text reset button and no results display

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/libcal.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Fixed the button height
- Fixed the button font size
-  Reserve Space should be sentence case, so “Reserve space.” 
- Vertically centered the table data for study places and persons
- Corrected the padding between `td`.
- 7/26
- Normal
- Normal
3. Navigate to list test page
4. Verify the button changes.
5. Verify the vertical centering on table view. No changes to the tablet or phone sizes.
6. Verify the changes to the padding on the `td`.
7. 16px after the photo for Specialist and Branches.
9. Specialist: 72px on name and expertise `td`s.
10. Places to study: 32px on photo, place, library, open/closed, features `td`s.
11. Branches: 80px on library, open/close, contact `td`s
- Is there a config:export in …

SUL23-577 SUL23-586: buttons and vertical centering on tables

---

src/components/node/stanford-page/home-page/today-hours.tsx
src/components/patterns/elements/select-list.tsx
src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- fixed the height of the search, toggles and filters to 40px
- Changed the `rounded-full` for just nothing selected and the `rounded-3xl` when there is a selection. 
- 7/26
- Normal
- Normal
1. Open Vercel
3. Navigate to test-list-page
4. Verify the heights of the search box, toggles and filters are 40.  The filters are 40.7 on a large screen
5. Verify the select box on the homepage is also full rounded without a selection and round-3xl with a selection.
[- SUL23-574](https://stanfordits.atlassian.net/browse/SUL23-574)
[- SUL23-575](https://stanfordits.atlassian.net/browse/SUL23-575)
[- …

SUL23-576 SUL23-575 SUL23-574: fixed height of toggle and filters

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- changed the descriptive `td` to `th scope=row` for a11y.
- 7/29
- Normal
- Normal
3. Navigate to list-test-page
4. Verify the td that has the name of the row is now `th scope=row`
[- SUL23-591](https://stanfordits.atlassian.net/browse/SUL23-591) …

SUL23-591: added the th row=scope for a11y

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- made "Open now" display in sentence case.
4. Verify...
- Other PRs
- …

SUL23-551: sentence case for branches and places to study

---

src/components/node/stanford-page/home-page/today-hours.tsx

4. Verify...
- Other PRs
- [AMP …

SUL23-482: set Todays hours title to h2

---

src/components/node/stanford-event/page-display.tsx
src/components/node/stanford-news/page-display.tsx
src/components/node/stanford-page/page-display.tsx
src/components/node/stanford-person/page-display.tsx
src/components/node/sul-library/page-display.tsx
src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
src/lib/hooks/useTodayLibraryHours.tsx

- **SUL23-597 Set timezones for any locale date/time stings**
- **Adjust next open hours logic**
4. Verify...
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a …

SUL23-597 Fix hour displays for next open date/time

---

src/components/views/sul-people/sul-people-table-view.tsx

- Set exact height to search box to match the toggles.  The toggles come out 40.69
- 8/13
- normal
- Normal
1.Navigate to...
4. Verify...
[- SUL23-574](https://stanfordits.atlassian.net/browse/SUL23-574)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

SUL23-574: setting exact height

---

src/lib/hooks/useTodayLibraryHours.tsx

- adding the `at` to the date/time string for the tables and homepage
- 8/13
- Normal
- Normal
1. Change the time on your computer.
2. Navigate to https://su-library-git-sul23-570-datetime-stanford-libraries.vercel.app/test-list-page
4. Verify for the closed option that it matches this pattern on the tables and the homepage.
Closed until today at [time]
Closed until tomorrow at [time]
Closed until [day of the week] at [time]
[- SUL23-570](https://stanfordits.atlassian.net/browse/SUL23-570)
[- SUL23-538](https://stanfordits.atlassian.net/browse/SUL23-538)
- [Accessibility Manual Test …

SUL23-580 SUL23-538: Added in the at to the time string

---

src/components/layout/header.tsx
src/components/menu/main-menu.tsx

- Added "Donate now" button to header
- Added "Donate now' link to Quick links in mobile view.
- Changed "Quick Links" to "Quick links"
- 8/14
- Normal
- Normal
3. Navigate to https://su-library-git-sul23-585-donate-stanford-libraries.vercel.app/
4. Verify the button is in the header and works on Desktop.
5. Verify the link is in the Quick Links at the end of the lis in Responsive.
[- SUL23-858](https://stanfordits.atlassian.net/browse/SUL23-585)
- [HTML …

SUL23-585: Adding Donate now button to header

---

src/components/layout/header.tsx
src/components/menu/main-menu.tsx

- Changes to the donate button
- Go to the original button color: Digital red
- Leave in the leading and padding for alignment
- Mobile menu:
- Left align the words “Quick links:”
- Use the spacing between the two rows of links for hte space below the words "Quick links:"
- 8/16
- Normal
- Normal
1. Navigate to Vercel: https://su-library-git-sul23-585-v2-stanford-libraries.vercel.app/
4. Verify the the changes above are done.
5. Review code.
[- SUL23-585](https://stanfordits.atlassian.net/browse/SUL23-585)
- [Accessibility Manual Test …

SUL23-585: Back to digital red

---

src/lib/hooks/useTodayLibraryHours.tsx

- this does what we want per the ticket.
- show closing minutes if they are not 00
- 8/16
- Normal
- Normal
4. Verify...
[- SUL23-600](https://stanfordits.atlassian.net/browse/SUL23-600) …

SUL23-600 show closing minutes if they are not 00

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- Added `Hours this week` as a default for libraries closed all week, like Cubberley
- 8/16
- normal
1.Navigate to https://su-library-git-sul23-570-closed-stanford-libraries.vercel.app/test-list-page
4. Verify there is no change on the homepage card.
5. Verify the text appears on the Cubberley and Tanner Branch page
[- SUL23-570](https://stanfordits.atlassian.net/browse/SUL23-570)
- [Accessibility Manual …

SUL-23-570: adding Hours this week for default

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- removed padding-left on heading row
- 8/16
- Normal
- Normal
1. Navigate to https://su-library-git-sul23-603-header-stanford-libraries.vercel.app/test-list-page
4. Verify on the branches table the library name aligns left with the column header.
[- SUL23-603](https://stanfordits.atlassian.net/browse/SUL23-603) …

SUL23-603: removed padding-left on branch name

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- On phone size, the toggle text centers on phone size.
- On phone size, the toggle has 10px margin bottom before selects starts.
- On desktop size, Matched the button padding to 9px  22px 
- 8/19
- normal
- normal
1. Navigate to https://su-library-git-sul23-604-stanford-libraries.vercel.app/test-list-page
4. Verify items listed above.
- Other PRs
- [Accessibility Manual Test …

SUL23-604: tweaking the toggle spacing

---

src/components/views/sul-people/sul-people-table-view.tsx

- changed the focus to not have red text and underline. 
- 8/29
- normal
- normal
1. Navigate to https://su-library-git-sul23-601-focus-state-stanford-libraries.vercel.app/test-list-page
4. Verify the SUL people toggles no longer have red text/underline when it is focused.  It is supposed to have a red text hover and the red border.
[- SUL23-601 ](https://stanfordits.atlassian.net/browse/SUL23-601)
- 
- …

SUL23-601: changed when focused to not be red with red underline

---

next-env.d.ts
src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
src/components/views/sul-people/sul-people-table-view.tsx
src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
src/components/views/view.tsx
src/lib/format-html.tsx

- added an action to the empty `form` tag to pass validation.
-  removed the `h2` from the table and used a `span` instead.
- removed the `Heading` component code since we aren't using it on the people table. (does this look right?)
- verified the people teasers were unchanged.
- Soon
- Normal
- Normal
1. Navigate to https://su-library-git-sul23-614-html-val-stanford-libraries.vercel.app/test-list-page
4. Verify no visible differences.
5. Verify passes html: https://validator.w3.org/nu
6. Verify the Heading removal caused no issues and was done correctly.
7. Review code.
- Other PRs
- Any other contextual information that might …

SUL23-614 SUL23-615: fixes for html validation

---

src/components/layout/library-footer.tsx

- Fixed font size
- 
- ASAP
- Normal
- Normal
1. Navigate to...
4. Verify text footer links are 19px and not 21px
- Other PRs
- [Browserstack](https://live.browserstack.com/dashboard) and link to …

SUL23-615: footer link size

---

src/components/node/stanford-person/page-display.tsx

- changed `Research` to `Expertise` on person page
- Soon
- Normal
- Normal
1. Navigate to test site
4. Verify Research was changed to Expertise on person page.
- Other PRs
- …

SUL23-617: changed to Expertise

---

src/components/paragraph/sul-collection.tsx
src/components/paragraph/sul-featured-collection.tsx

- SUL23-481 | hardcode headings for feature collections
1. Review preview
2. Verify the headings are appearing correctly and fulfill accessibility requirements
3. Review code
- SUL23-481

SUL23-481 | hardcode headings for feature collections

---

src/components/node/stanford-news/page-display.tsx

- SUL23-647 | add margin bottom to Dek text
1. Navigate to a news item on preview
4. Verify that there is spacing underneath the Dek
5. Review code
- SUL23-647

SUL23-647 | add margin bottom to Dek text

---

src/components/patterns/toggle-option.tsx

- remove underline from checked/selected state
4. Verify that when selected, no underline appears under the text
5. Review code
- SUL23-649 |

SUL23-649 | remove underline from checked/selected state

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- SUL23-650 | remove margin spacing
4. Verify...
- SUL23-650

SUL23-650 | remove margin spacing

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- adjust select list to fit text
1. Navigate to [preview `/test-list-page`](https://su-library-git-feature-sul23-652-stanford-libraries.vercel.app/test-list-page)
4. Verify that the select list filters match the [updated mock](https://www.figma.com/design/E6rFFnHIs7ch0oK5j9C1Wc/Tabular-view-and-Filtering?node-id=1732-679&t=5dqQFZ9YcdRhtq0a-1)
5. Review code
- SUL23-652

SUL23-652 | adjust select list to fit text

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- SUL23-650 | update font to match mocks
1. Review code
- SUL23-650

SUL23-650 | update font to match mocks

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- SUL23-652 | adjust filter width and margin bottom
1. Review code
- SUL23-652

SUL23-652 | adjust filter width and margin bottom

---

app/[...slug]/page.tsx
src/components/patterns/headingList.tsx
src/components/patterns/on-this-page.tsx

- SUL23-638 | update file and heading naming and update intersection observer config
- when possible
1. Review preview: https://su-library-git-feature-sul23-638-qafixes-stanford-libraries.vercel.app/about-stanford-libraries
4. Verify both headings are "On this page" for desktop and mobile
5. Review code
- SUL23-638

SUL23-638 | update file and heading naming and update intersection observer config

---

app/[...slug]/page.tsx
src/components/node/stanford-page/page-display.tsx

- SUL23-654 | swap out article for div and add article wrapper to main content
1. Navigate to preview: https://su-library-git-bug-sul23-654-articlewarning-stanford-libraries.vercel.app/explore-collections
4. Verify that the page appears the same as production
5. Copy link and navigate to https://validator.w3.org/
6. Paste link and check. No article warning should appear
7. Review other basic pages on the site
8. Review code
- SUL23-654

SUL23-654 | swap out article for div and add article wrapper to main content

---

app/[...slug]/metadata.tsx

- SUL23-664 | update to Stanford Libraries for meta data title
1. Review code
- SUL23-664

SUL23-664 | update to Stanford Libraries for meta data title

---

src/components/views/stanford-news/filtering-news-card-view.client.tsx

- SUL23-666 | add typography to match places to study
- asap
4. Verify...
- SUL23-666

SUL23-666 | add typography to match places to study

---

src/components/views/stanford-news/filtering-news-card-view.client.tsx

- SUL23-668 | change last 12 months to last 90 days
- asap
1. Review code
- SUL23-668 | change last 12 months to last 90 days

SUL23-668 | change last 12 months to last 90 days

---

src/components/views/stanford-news/filtering-news-card-view.client.tsx
src/components/views/sul-people/sul-people-table-view.tsx

Better css only logic for reset button hide/show

Pure css to hide/show clear button on text fields

---

src/lib/format-html.tsx
src/styles/globals.css

- SUL23-663 | fix oembed width and alignment issue
- asap

SUL23-663 | fix oembed width and alignment issue

---

src/components/node/stanford-news/page-display.tsx

- SUL23-693 | fix html validation issue for social share
1. Navigate to a [news page](https://su-library-git-byg-sul23-693-htmlvalidation-stanford-libraries.vercel.app/news/stanford-libraries-welcomes-danielle-gensch)
2. Plug the URL into [HTML validator](https://validator.w3.org/nu/)  
3. Verify that the a tag error no longer appears
4. Review code
- SUL23-693

SUL23-693 | fix html validation issue for social share

---

src/components/node/sul-library/library-header.tsx

- SUL23-691 | add id to branch page h1 to fix arialabelledby html validation error
- when possible
1. Navigate to any branch page (e.g. https://su-library-git-bug-sul23-691-arialabelledby-stanford-libraries.vercel.app/libraries/east-asia-library or https://su-library-git-bug-sul23-691-arialabelledby-stanford-libraries.vercel.app/libraries/archive-recorded-sound)
2. Copy and paste link into html validator: https://validator.w3.org/
3. Confirm that the arialabelledby error no longer appears
4. Review code 🪴 
- SUL23-691

SUL23-691 | add id to branch page h1 to fix arialabelledby html validation error

---

src/components/paragraph/stanford-card.tsx
src/components/patterns/card.tsx

- SUL23-707 | add caption option to card
- 1/21
1. Navigate to preview: https://su-library-git-feature-sul23-707-cardcaption-stanford-libraries.vercel.app/new-cards
2. Confirm that the card caption works
3. Review code
- SUL23-707

SUL23-707 | add caption option to card

---

app/page.tsx
src/components/node/stanford-page/home-page/home-page-banner.tsx

- SUL23-701 | add homepage h1
- asap
1. Navigate to home page review
2. Verify h1 appears in code
3. Review code
- SUL23-701 | add homepage h1

SUL23-701 | add homepage h1

---

README.md

- @jenbreese has brought to my attention that we don’t have clear documentation on the PR merging/release workflow in our repo(s). I’ve documented the PR workflow to the best of my understanding. If everything looks good, I’d like to copy-paste it over to the summer and press repos as well. Please share all the feedback and thoughts! 😎 
1. Review **Pull Request and Development Workflow Guide** section of the readme
2. Provide feedback on the workflow 
3. 🌱

nojira | update readme to include PR workflow

---

src/components/paragraph/rows/rows.tsx
src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx

- SUL23-702 SUL23-704 | adjust rows spacing and sync card font-size
4. Verify...
- SUL23-702 
- SUL23-704

SUL23-702 SUL23-704 | adjust rows spacing and sync card font-size

---

src/components/layout/header.tsx
src/components/layout/library-footer.tsx
src/components/paragraph/stanford-card.tsx
src/components/paragraph/sul-home-image/sul-home-image.tsx
src/components/patterns/elements/lockup/lockup-logo.tsx
src/components/patterns/elements/lockup/lockup.tsx

- SUL23-704 | adjust horizontal card spacing for lg
- SUL23-728 | adjust header and update lockup in footer
- Asap
1. Review code
- SUL23-704 
- SUL23-728

SUL23-704 SUL23-728 | adjust horizontal card spacing for lg, adjust header and update lockup in footer

---

app/[...slug]/page.tsx
src/components/paragraph/stanford-lists.tsx
src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
src/components/patterns/headingList.tsx
src/components/patterns/on-this-page.tsx
src/components/patterns/sul-accordion.tsx

https://stanfordits.atlassian.net/browse/SUL23-741
https://stanfordits.atlassian.net/browse/SUL23-742
https://stanfordits.atlassian.net/browse/SUL23-743
https://stanfordits.atlassian.net/browse/SUL23-745

SUL23-741, SUL23-742, SUL23-743, SUL23-745: Bug fixes and reorder elements

---

src/components/search/search-page.tsx
src/components/views/search-search/search-search-view.tsx

- SUL23-726 | update search page design
1. Navigate to https://su-library-git-feature-sul23-726-search-stanford-libraries.vercel.app/search
4. Verify that the search bar and results match the[ figma mock](https://www.figma.com/design/vFJQdfoibVOgqU8w4RSYmX/Search-results?node-id=62-309&t=Z0ptv4iEqv9wocSq-1)
5. Review code
- SUL23-726

SUL23-726 | update search page

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
src/components/views/sul-study-place/filtering-table/study-place-table.tsx

- Styled and added the Additional Info below the Features
- soon
- High
- High
3. Navigate to a place to study and add content to the field.
4. Add content with and without html.
5. Try adding the link to make sure it look ok too
6. Verify the new field looks good on all sizes.
7. Verify nothing happens if no content is added.
[- SUL23-714](https://stanfordits.atlassian.net/browse/SUL23-714)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/e …

SUL23-714: Adding the additional info to the study place table

---

src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx

- Consolidated features, Reservations and notes into one column.
- 2/27
- High
- High
3. Add a note to one of the study areas
4. Verify the Features, Reservations and Note are ordered correctly. Note, the features had a background of grey in medium and down breakpoints. I did not add that to the new ones. There weren't designs or mention of adding it to the new fields.
[- SUL23-714](https://stanfordits.atlassian.net/issues/SUL23-714)
- [Accessibility Manual Test …

SUL23-714: combined cols and added spacing

---

src/components/layout/header.tsx

- SUL23-753 | fix list html validation error in header
- asap
1. Review code
- SUL23-753

SUL23-753 | fix list html validation error in header

---

src/components/layout/header.tsx

- Changed the link for the donate button in the header, per https://stanfordits.atlassian.net/browse/SUL23-749
4. Verify...
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it …

SUL23-749: Updated the link for donate button

---

src/components/layout/global-footer.tsx
src/components/node/stanford-course/card.tsx
src/components/node/stanford-event-series/page-display.tsx
src/components/node/stanford-event/card.tsx
src/components/node/stanford-event/page-display.tsx
src/components/node/stanford-news/card.tsx
src/components/node/stanford-news/list-item.tsx
src/components/node/stanford-news/page-display.tsx
src/components/node/stanford-page/card.tsx
src/components/node/stanford-person/horizontal-card.tsx
src/components/node/stanford-person/list-item.tsx
src/components/node/stanford-person/vertical-card.tsx
src/components/node/sul-library/card.tsx
src/components/paragraph/stanford-image-gallery.tsx
src/components/paragraph/stanford-media-caption.tsx
src/components/paragraph/sul-contact-card/manual-fields-card.tsx
src/components/paragraph/sul-contact-card/node-reference-card.tsx
src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
src/components/patterns/banner.tsx
src/components/patterns/card.tsx
src/components/patterns/horizontal-card.tsx
src/lib/format-html.tsx
src/styles/tailwind/plugins/base/base.js

- SUL23-751 | rework fonts
1. Navigate to https://su-library-git-feature-sul23-751-fonts-stanford-libraries.vercel.app/
2. Verify that the fonts throughout the website match what is defined in [figma mock](https://www.figma.com/design/yv3myOg2GYptQzpYohIdwo/Home-page?node-id=2496-2654&m=dev)
3. Review code
- SUL23-751

SUL23-751 | rework fonts

---

src/components/layout/library-footer.tsx
src/components/node/stanford-event/card.tsx
src/components/node/stanford-person/vertical-card.tsx
src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
src/components/patterns/card.tsx
src/components/patterns/horizontal-card.tsx
src/components/views/sul-study-place/study-place-filtering.tsx
src/styles/tailwind/plugins/base/base.js

- SUL23-751 | implement font feedback
- when possible
2. Verify that the following changes have been made:
- Library branch card + People card: font mismatch 
- Cards/Events Card Heading letter-spacing -0.2px
- On View Horizontal Card Heading font-size: 32px
- Text area H2 font-size: 44px
- Text area H3 font-size 32px
- Footer H2 font-size 24px, margin-bottom: 1rem
3. Review code
- SUL23-751

SUL23-751 | implement font feedback

---

src/lib/gql/__generated__/drupal.d.tsx

Updated graphql queries for the changes in https://github.com/SU-SWS/ace-stanfordlagunita/pull/177
4. Verify...
- Other PRs
- …

Updated graphql queries

---

src/components/layout/header.tsx
src/components/menu/main-menu.tsx
src/components/patterns/elements/lockup/lockup-logo.tsx
src/components/patterns/elements/lockup/lockup.tsx

- SUL23-787 SUL23-788 | resolve wrapping bug at specific breakpoints for main and secondary nav
1. Navigate to preview site
2. Verify that the changes match the [mock at 992px and 1274px](https://www.figma.com/design/yv3myOg2GYptQzpYohIdwo/Home-page?node-id=2974-5550&t=YYUkA15We1lphowF-1)
3. Review code
- - SUL23-787 
- SUL23-788

SUL23-787 SUL23-788 | resolve wrapping bug at specific breakpoints for main and secondary nav

---

src/components/patterns/horizontal-card.tsx

- SUL23-789 | add conditional spacing for content
- 5/21
2. Verify that the content spacing appears with the rosette
3. Review code 👾 
- SUL23-789

SUL23-789 | add conditional spacing for content

---

app/[...slug]/page.tsx
app/calendar/[id]/page.tsx
app/not-found.tsx
app/search/layout.tsx
app/study-place/features/[uuid]/page.tsx
src/components/node/stanford-person/libguide.tsx
src/components/patterns/horizontal-card.tsx
src/components/patterns/internal-header-banner.tsx
src/styles/tailwind/plugins/base/base.js

- SUL23-789 | update horizontal card superhead font size
- SUL23-793 SUL23-794 SUL23-795 | update header banner page font sizes
- EOD would be nice otherwise when possible 
1. Review code ✨ 
- SUL23-789
- SUL23-793
- SUL23-794
- SUL23-795

SUL23-789 SUL23-793 SUL23-794 | implement qa feedback for horizontal card and page header banner

---

app/[...slug]/page.tsx

- SUL23-795 | tweak news type font size
- EOD Thursday 05/29
1. Review code 👾 
- SUL23-795

SUL23-795 | tweak news type font size

---

src/components/layout/library-footer.tsx

- SUL23-806 | Update about us link in footer
4. Verify that it links to the desired page
5. Review code
- SUL23-806

SUL23-806 | Update about us link in footer

---

app/page.tsx
src/components/node/stanford-news/page-display.tsx
src/components/node/stanford-page/page-display.tsx
src/components/node/stanford-person/page-display.tsx
src/components/node/sul-library/page-display.tsx

- SUL23-776 | fix last updated section for a11y
- Friday, July 18
1.Navigate to homepage
2. Verify that the Last Updated appears the same as PROD
3. Confirm that site improve extension doesn't throw an error
4. Review code 🐛 
- SUL23-776

SUL23-776 | fix last updated section for a11y

---

.github/workflows/build_lint.yml
src/components/patterns/icons/RosetteIcon.tsx

- SUL23-828 | remove rosette id
- Thursday, Aug, 21
2. Verify using html validator that the dupe id error no longer appears
3. Review code
- SUL23-828

SUL23-828 | remove rosette id

---

src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx

- SUL23-833 | update padding right to modular spacer for branch center list table
- Thursday, Aug 21
1. Navigate to preview site: https://su-library-git-bug-sul23-833-stanford-libraries.vercel.app/list-view-branches-and-centers
2. Verify that between 1200-1350px, the address no longer breaks out of the table/screen
3. Review code
- SUL23-833

SUL23-833 | update padding right to modular spacer for branch center list table

---

app/api/people/search/route.tsx
src/lib/gql/__generated__/drupal.d.tsx
src/lib/gql/__generated__/queries.ts
src/lib/gql/view-queries.drupal.gql

- We need to return research interests and person types in the API response, so we add those here.
- Fairly high, since this is a blocker for the SUL team to continue customization of search
1. You can check to make sure the API is responding correctly by using the preview environment.  Sample link: https://su-library-git-sul23-837-stanford-libraries.vercel.app/api/people/search?q=Marine%20biology%20sustainability%20biodiversity  Of course, you can use other search terms.
2. Ensure the API is including information about research interests (under the `research` key), and personTypes (under the `personTypes` key).
3. Check code.
- Is there a config:export in this PR that changes the config sync directory? NO
- Does this PR impact any particular …

SUL23-837: Added research and person types to person search API results

---

src/components/paragraph/sul-location-hour/sul-location-hour.tsx
src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx

- SUL23-841 | update library hours alert to conditionally display
1. Git blame 👉 past Rebecca (not sure why I didn't have this implemented by default 🤔 )
3. Navigate to preview site: https://su-library-git-bug-sul23-841-stanford-libraries.vercel.app/
4. Verify that the alert doesn't display
5. Review code
- SUL23-841

SUL23-841 | update library hours alert to conditionally display

---

src/components/node/stanford-event/list-item.tsx
src/components/views/stanford-events/events-card-view.tsx

- SUL23-835 SUL23-836 | adjust event list item responsive
1. Navigate to...
2. Verify...
3. Review code
- SUL23-835
- SUL23-836

SUL23-835 SUL23-836 | adjust event list item responsive
